# DO NOT EDIT THIS FILE!
#
# Python module subnetworkConnection__POA generated by omniidl

import omniORB
omniORB.updateModule("subnetworkConnection__POA")

# ** 1. Stub files contributing to this module
import subnetworkConnection_idl

# ** 2. Sub-modules

# ** 3. End
