# DO NOT EDIT THIS FILE!
#
# Python module emsSessionFactory__POA generated by omniidl

import omniORB
omniORB.updateModule("emsSessionFactory__POA")

# ** 1. Stub files contributing to this module
import emsSessionFactory_idl

# ** 2. Sub-modules

# ** 3. End
