# DO NOT EDIT THIS FILE!
#
# Python module notifications generated by omniidl

import omniORB
omniORB.updateModule("notifications")

# ** 1. Stub files contributing to this module
import notifications_idl

# ** 2. Sub-modules

# ** 3. End
