# DO NOT EDIT THIS FILE!
#
# Python module emsSession generated by omniidl

import omniORB
omniORB.updateModule("emsSession")

# ** 1. Stub files contributing to this module
import emsSession_idl

# ** 2. Sub-modules

# ** 3. End
