# DO NOT EDIT THIS FILE!
#
# Python module emsMgr generated by omniidl

import omniORB
omniORB.updateModule("emsMgr")

# ** 1. Stub files contributing to this module
import emsMgr_idl

# ** 2. Sub-modules

# ** 3. End
