# DO NOT EDIT THIS FILE!
#
# Python module managedElementManager__POA generated by omniidl

import omniORB
omniORB.updateModule("managedElementManager__POA")

# ** 1. Stub files contributing to this module
import managedElementManager_idl

# ** 2. Sub-modules

# ** 3. End
