# DO NOT EDIT THIS FILE!
#
# Python module topologicalLink__POA generated by omniidl

import omniORB
omniORB.updateModule("topologicalLink__POA")

# ** 1. Stub files contributing to this module
import topologicalLink_idl

# ** 2. Sub-modules

# ** 3. End
