# DO NOT EDIT THIS FILE!
#
# Python module nmsSession generated by omniidl

import omniORB
omniORB.updateModule("nmsSession")

# ** 1. Stub files contributing to this module
import nmsSession_idl

# ** 2. Sub-modules

# ** 3. End
