# DO NOT EDIT THIS FILE!
#
# Python module topologicalLink generated by omniidl

import omniORB
omniORB.updateModule("topologicalLink")

# ** 1. Stub files contributing to this module
import topologicalLink_idl

# ** 2. Sub-modules

# ** 3. End
