# DO NOT EDIT THIS FILE!
#
# Python module notifications__POA generated by omniidl

import omniORB
omniORB.updateModule("notifications__POA")

# ** 1. Stub files contributing to this module
import notifications_idl

# ** 2. Sub-modules

# ** 3. End
