# DO NOT EDIT THIS FILE!
#
# Python module session generated by omniidl

import omniORB
omniORB.updateModule("session")

# ** 1. Stub files contributing to this module
import session_idl

# ** 2. Sub-modules

# ** 3. End
