# DO NOT EDIT THIS FILE!
#
# Python module multiLayerSubnetwork__POA generated by omniidl

import omniORB
omniORB.updateModule("multiLayerSubnetwork__POA")

# ** 1. Stub files contributing to this module
import multiLayerSubnetwork_idl

# ** 2. Sub-modules

# ** 3. End
