# DO NOT EDIT THIS FILE!
#
# Python module transmissionParameters generated by omniidl

import omniORB
omniORB.updateModule("transmissionParameters")

# ** 1. Stub files contributing to this module
import transmissionParameters_idl

# ** 2. Sub-modules

# ** 3. End
