# DO NOT EDIT THIS FILE!
#
# Python module terminationPoint generated by omniidl

import omniORB
omniORB.updateModule("terminationPoint")

# ** 1. Stub files contributing to this module
import terminationPoint_idl

# ** 2. Sub-modules

# ** 3. End
