# DO NOT EDIT THIS FILE!
#
# Python module globaldefs generated by omniidl

import omniORB
omniORB.updateModule("globaldefs")

# ** 1. Stub files contributing to this module
import globaldefs_idl

# ** 2. Sub-modules

# ** 3. End
