# Python stubs generated by omniidl from common.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)

# #include "globaldefs.idl"
import globaldefs_idl
_0_globaldefs = omniORB.openModule("globaldefs")
_0_globaldefs__POA = omniORB.openModule("globaldefs__POA")

#
# Start of module "common"
#
__name__ = "common"
_0_common = omniORB.openModule("common", r"common.idl")
_0_common__POA = omniORB.openModule("common__POA", r"common.idl")


# typedef ... Capability_T
class Capability_T (_0_globaldefs.NameAndStringValue_T):
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/common/Capability_T:1.0"

_0_common.Capability_T = Capability_T
_0_common._d_Capability_T  = omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0"]
_0_common._ad_Capability_T = (omniORB.tcInternal.tv_alias, Capability_T._NP_RepositoryId, "Capability_T", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NameAndStringValue_T:1.0"])
_0_common._tc_Capability_T = omniORB.tcInternal.createTypeCode(_0_common._ad_Capability_T)
omniORB.registerType(Capability_T._NP_RepositoryId, _0_common._ad_Capability_T, _0_common._tc_Capability_T)
del Capability_T

# typedef ... CapabilityList_T
class CapabilityList_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/common/CapabilityList_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_common.CapabilityList_T = CapabilityList_T
_0_common._d_CapabilityList_T  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/common/Capability_T:1.0"], 0)
_0_common._ad_CapabilityList_T = (omniORB.tcInternal.tv_alias, CapabilityList_T._NP_RepositoryId, "CapabilityList_T", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/common/Capability_T:1.0"], 0))
_0_common._tc_CapabilityList_T = omniORB.tcInternal.createTypeCode(_0_common._ad_CapabilityList_T)
omniORB.registerType(CapabilityList_T._NP_RepositoryId, _0_common._ad_CapabilityList_T, _0_common._tc_CapabilityList_T)
del CapabilityList_T

# interface Common_I
_0_common._d_Common_I = (omniORB.tcInternal.tv_objref, "IDL:mtnm.tmforum.org/common/Common_I:1.0", "Common_I")
omniORB.typeMapping["IDL:mtnm.tmforum.org/common/Common_I:1.0"] = _0_common._d_Common_I
_0_common.Common_I = omniORB.newEmptyClass()
class Common_I :
    _NP_RepositoryId = _0_common._d_Common_I[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_common.Common_I = Common_I
_0_common._tc_Common_I = omniORB.tcInternal.createTypeCode(_0_common._d_Common_I)
omniORB.registerType(Common_I._NP_RepositoryId, _0_common._d_Common_I, _0_common._tc_Common_I)

# Common_I operations and attributes
Common_I._d_setNativeEMSName = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], (omniORB.tcInternal.tv_string,0)), (), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
Common_I._d_setUserLabel = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_boolean), (), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
Common_I._d_setOwner = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], (omniORB.tcInternal.tv_string,0)), (), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
Common_I._d_getCapabilities = ((), (omniORB.typeMapping["IDL:mtnm.tmforum.org/common/CapabilityList_T:1.0"], ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})

# Common_I object reference
class _objref_Common_I (CORBA.Object):
    _NP_RepositoryId = Common_I._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def setNativeEMSName(self, *args):
        return _omnipy.invoke(self, "setNativeEMSName", _0_common.Common_I._d_setNativeEMSName, args)

    def setUserLabel(self, *args):
        return _omnipy.invoke(self, "setUserLabel", _0_common.Common_I._d_setUserLabel, args)

    def setOwner(self, *args):
        return _omnipy.invoke(self, "setOwner", _0_common.Common_I._d_setOwner, args)

    def getCapabilities(self, *args):
        return _omnipy.invoke(self, "getCapabilities", _0_common.Common_I._d_getCapabilities, args)

    __methods__ = ["setNativeEMSName", "setUserLabel", "setOwner", "getCapabilities"] + CORBA.Object.__methods__

omniORB.registerObjref(Common_I._NP_RepositoryId, _objref_Common_I)
_0_common._objref_Common_I = _objref_Common_I
del Common_I, _objref_Common_I

# Common_I skeleton
__name__ = "common__POA"
class Common_I (PortableServer.Servant):
    _NP_RepositoryId = _0_common.Common_I._NP_RepositoryId


    _omni_op_d = {"setNativeEMSName": _0_common.Common_I._d_setNativeEMSName, "setUserLabel": _0_common.Common_I._d_setUserLabel, "setOwner": _0_common.Common_I._d_setOwner, "getCapabilities": _0_common.Common_I._d_getCapabilities}

Common_I._omni_skeleton = Common_I
_0_common__POA.Common_I = Common_I
omniORB.registerSkeleton(Common_I._NP_RepositoryId, Common_I)
del Common_I
__name__ = "common"

#
# End of module "common"
#
__name__ = "common_idl"

_exported_modules = ( "common", )

# The end.
