# Python stubs generated by omniidl from emsMgr.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)

# #include "globaldefs.idl"
import globaldefs_idl
_0_globaldefs = omniORB.openModule("globaldefs")
_0_globaldefs__POA = omniORB.openModule("globaldefs__POA")
# #include "common.idl"
import common_idl
_0_common = omniORB.openModule("common")
_0_common__POA = omniORB.openModule("common__POA")
# #include "transmissionParameters.idl"
import transmissionParameters_idl
_0_transmissionParameters = omniORB.openModule("transmissionParameters")
_0_transmissionParameters__POA = omniORB.openModule("transmissionParameters__POA")
# #include "terminationPoint.idl"
import terminationPoint_idl
_0_terminationPoint = omniORB.openModule("terminationPoint")
_0_terminationPoint__POA = omniORB.openModule("terminationPoint__POA")
# #include "subnetworkConnection.idl"
import subnetworkConnection_idl
_0_subnetworkConnection = omniORB.openModule("subnetworkConnection")
_0_subnetworkConnection__POA = omniORB.openModule("subnetworkConnection__POA")
# #include "managedElement.idl"
import managedElement_idl
_0_managedElement = omniORB.openModule("managedElement")
_0_managedElement__POA = omniORB.openModule("managedElement__POA")
# #include "topologicalLink.idl"
import topologicalLink_idl
_0_topologicalLink = omniORB.openModule("topologicalLink")
_0_topologicalLink__POA = omniORB.openModule("topologicalLink__POA")
# #include "protection.idl"
import protection_idl
_0_protection = omniORB.openModule("protection")
_0_protection__POA = omniORB.openModule("protection__POA")
# #include "multiLayerSubnetwork.idl"
import multiLayerSubnetwork_idl
_0_multiLayerSubnetwork = omniORB.openModule("multiLayerSubnetwork")
_0_multiLayerSubnetwork__POA = omniORB.openModule("multiLayerSubnetwork__POA")
# #include "CosNotification.idl"
import CosNotification_idl
_0_CosNotification = omniORB.openModule("CosNotification")
_0_CosNotification__POA = omniORB.openModule("CosNotification__POA")
# #include "notifications.idl"
import notifications_idl
_0_notifications = omniORB.openModule("notifications")
_0_notifications__POA = omniORB.openModule("notifications__POA")

#
# Start of module "emsMgr"
#
__name__ = "emsMgr"
_0_emsMgr = omniORB.openModule("emsMgr", r"emsMgr.idl")
_0_emsMgr__POA = omniORB.openModule("emsMgr__POA", r"emsMgr.idl")


# struct EMS_T
_0_emsMgr.EMS_T = omniORB.newEmptyClass()
class EMS_T (omniORB.StructBase):
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/emsMgr/EMS_T:1.0"

    def __init__(self, name, userLabel, nativeEMSName, owner, emsVersion, type, additionalInfo):
        self.name = name
        self.userLabel = userLabel
        self.nativeEMSName = nativeEMSName
        self.owner = owner
        self.emsVersion = emsVersion
        self.type = type
        self.additionalInfo = additionalInfo

_0_emsMgr.EMS_T = EMS_T
_0_emsMgr._d_EMS_T  = (omniORB.tcInternal.tv_struct, EMS_T, EMS_T._NP_RepositoryId, "EMS_T", "name", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "userLabel", (omniORB.tcInternal.tv_string,0), "nativeEMSName", (omniORB.tcInternal.tv_string,0), "owner", (omniORB.tcInternal.tv_string,0), "emsVersion", (omniORB.tcInternal.tv_string,0), "type", (omniORB.tcInternal.tv_string,0), "additionalInfo", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0"])
_0_emsMgr._tc_EMS_T = omniORB.tcInternal.createTypeCode(_0_emsMgr._d_EMS_T)
omniORB.registerType(EMS_T._NP_RepositoryId, _0_emsMgr._d_EMS_T, _0_emsMgr._tc_EMS_T)
del EMS_T

# typedef ... AlarmSerialNoList_T
class AlarmSerialNoList_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/emsMgr/AlarmSerialNoList_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_emsMgr.AlarmSerialNoList_T = AlarmSerialNoList_T
_0_emsMgr._d_AlarmSerialNoList_T  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0_emsMgr._ad_AlarmSerialNoList_T = (omniORB.tcInternal.tv_alias, AlarmSerialNoList_T._NP_RepositoryId, "AlarmSerialNoList_T", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0_emsMgr._tc_AlarmSerialNoList_T = omniORB.tcInternal.createTypeCode(_0_emsMgr._ad_AlarmSerialNoList_T)
omniORB.registerType(AlarmSerialNoList_T._NP_RepositoryId, _0_emsMgr._ad_AlarmSerialNoList_T, _0_emsMgr._tc_AlarmSerialNoList_T)
del AlarmSerialNoList_T

# struct ClockSourceStatus_T
_0_emsMgr.ClockSourceStatus_T = omniORB.newEmptyClass()
class ClockSourceStatus_T (omniORB.StructBase):
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/emsMgr/ClockSourceStatus_T:1.0"

    def __init__(self, name, nativeEMSName, status, timingMode, quality, workingMode, additionalInfo):
        self.name = name
        self.nativeEMSName = nativeEMSName
        self.status = status
        self.timingMode = timingMode
        self.quality = quality
        self.workingMode = workingMode
        self.additionalInfo = additionalInfo

_0_emsMgr.ClockSourceStatus_T = ClockSourceStatus_T
_0_emsMgr._d_ClockSourceStatus_T  = (omniORB.tcInternal.tv_struct, ClockSourceStatus_T, ClockSourceStatus_T._NP_RepositoryId, "ClockSourceStatus_T", "name", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "nativeEMSName", (omniORB.tcInternal.tv_string,0), "status", (omniORB.tcInternal.tv_string,0), "timingMode", (omniORB.tcInternal.tv_string,0), "quality", (omniORB.tcInternal.tv_string,0), "workingMode", (omniORB.tcInternal.tv_string,0), "additionalInfo", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0"])
_0_emsMgr._tc_ClockSourceStatus_T = omniORB.tcInternal.createTypeCode(_0_emsMgr._d_ClockSourceStatus_T)
omniORB.registerType(ClockSourceStatus_T._NP_RepositoryId, _0_emsMgr._d_ClockSourceStatus_T, _0_emsMgr._tc_ClockSourceStatus_T)
del ClockSourceStatus_T

# typedef ... ClockSourceStatusList_T
class ClockSourceStatusList_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/emsMgr/ClockSourceStatusList_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_emsMgr.ClockSourceStatusList_T = ClockSourceStatusList_T
_0_emsMgr._d_ClockSourceStatusList_T  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/emsMgr/ClockSourceStatus_T:1.0"], 0)
_0_emsMgr._ad_ClockSourceStatusList_T = (omniORB.tcInternal.tv_alias, ClockSourceStatusList_T._NP_RepositoryId, "ClockSourceStatusList_T", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/emsMgr/ClockSourceStatus_T:1.0"], 0))
_0_emsMgr._tc_ClockSourceStatusList_T = omniORB.tcInternal.createTypeCode(_0_emsMgr._ad_ClockSourceStatusList_T)
omniORB.registerType(ClockSourceStatusList_T._NP_RepositoryId, _0_emsMgr._ad_ClockSourceStatusList_T, _0_emsMgr._tc_ClockSourceStatusList_T)
del ClockSourceStatusList_T

# interface EMSMgr_I
_0_emsMgr._d_EMSMgr_I = (omniORB.tcInternal.tv_objref, "IDL:mtnm.tmforum.org/emsMgr/EMSMgr_I:1.0", "EMSMgr_I")
omniORB.typeMapping["IDL:mtnm.tmforum.org/emsMgr/EMSMgr_I:1.0"] = _0_emsMgr._d_EMSMgr_I
_0_emsMgr.EMSMgr_I = omniORB.newEmptyClass()
class EMSMgr_I (_0_common.Common_I):
    _NP_RepositoryId = _0_emsMgr._d_EMSMgr_I[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_emsMgr.EMSMgr_I = EMSMgr_I
_0_emsMgr._tc_EMSMgr_I = omniORB.tcInternal.createTypeCode(_0_emsMgr._d_EMSMgr_I)
omniORB.registerType(EMSMgr_I._NP_RepositoryId, _0_emsMgr._d_EMSMgr_I, _0_emsMgr._tc_EMSMgr_I)

# EMSMgr_I operations and attributes
EMSMgr_I._d_getEMS = ((), (omniORB.typeMapping["IDL:mtnm.tmforum.org/emsMgr/EMS_T:1.0"], ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
EMSMgr_I._d_getAllTopLevelSubnetworks = ((omniORB.tcInternal.tv_ulong, ), (omniORB.typeMapping["IDL:mtnm.tmforum.org/multiLayerSubnetwork/SubnetworkList_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/multiLayerSubnetwork/SubnetworkIterator_I:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
EMSMgr_I._d_getAllTopLevelSubnetworkNames = ((omniORB.tcInternal.tv_ulong, ), (omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributesList_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributesIterator_I:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
EMSMgr_I._d_getAllTopLevelTopologicalLinks = ((omniORB.tcInternal.tv_ulong, ), (omniORB.typeMapping["IDL:mtnm.tmforum.org/topologicalLink/TopologicalLinkList_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/topologicalLink/TopologicalLinkIterator_I:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
EMSMgr_I._d_getAllTopLevelTopologicalLinkNames = ((omniORB.tcInternal.tv_ulong, ), (omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributesList_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributesIterator_I:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
EMSMgr_I._d_getTopLevelTopologicalLink = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], ), (omniORB.typeMapping["IDL:mtnm.tmforum.org/topologicalLink/TopologicalLink_T:1.0"], ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
EMSMgr_I._d_getAllEMSAndMEActiveAlarms = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/notifications/ProbableCauseList_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/notifications/PerceivedSeverityList_T:1.0"], omniORB.tcInternal.tv_ulong), (omniORB.typeMapping["IDL:mtnm.tmforum.org/notifications/EventList_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/notifications/EventIterator_I:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
EMSMgr_I._d_getAllEMSSystemActiveAlarms = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/notifications/PerceivedSeverityList_T:1.0"], omniORB.tcInternal.tv_ulong), (omniORB.typeMapping["IDL:mtnm.tmforum.org/notifications/EventList_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/notifications/EventIterator_I:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
EMSMgr_I._d_getObjectRootAlarms = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/Time_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/Time_T:1.0"], omniORB.tcInternal.tv_ulong), (omniORB.typeMapping["IDL:mtnm.tmforum.org/notifications/EventList_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/notifications/EventIterator_I:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
EMSMgr_I._d_getObjectClockSourceStatus = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], ), (omniORB.typeMapping["IDL:mtnm.tmforum.org/emsMgr/ClockSourceStatusList_T:1.0"], ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
EMSMgr_I._d_acknowledgeAlarms = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/emsMgr/AlarmSerialNoList_T:1.0"], ), (omniORB.typeMapping["IDL:mtnm.tmforum.org/emsMgr/AlarmSerialNoList_T:1.0"], ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
EMSMgr_I._d_unacknowledgeAlarms = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/emsMgr/AlarmSerialNoList_T:1.0"], ), (omniORB.typeMapping["IDL:mtnm.tmforum.org/emsMgr/AlarmSerialNoList_T:1.0"], ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})

# EMSMgr_I object reference
class _objref_EMSMgr_I (_0_common._objref_Common_I):
    _NP_RepositoryId = EMSMgr_I._NP_RepositoryId

    def __init__(self):
        _0_common._objref_Common_I.__init__(self)

    def getEMS(self, *args):
        return _omnipy.invoke(self, "getEMS", _0_emsMgr.EMSMgr_I._d_getEMS, args)

    def getAllTopLevelSubnetworks(self, *args):
        return _omnipy.invoke(self, "getAllTopLevelSubnetworks", _0_emsMgr.EMSMgr_I._d_getAllTopLevelSubnetworks, args)

    def getAllTopLevelSubnetworkNames(self, *args):
        return _omnipy.invoke(self, "getAllTopLevelSubnetworkNames", _0_emsMgr.EMSMgr_I._d_getAllTopLevelSubnetworkNames, args)

    def getAllTopLevelTopologicalLinks(self, *args):
        return _omnipy.invoke(self, "getAllTopLevelTopologicalLinks", _0_emsMgr.EMSMgr_I._d_getAllTopLevelTopologicalLinks, args)

    def getAllTopLevelTopologicalLinkNames(self, *args):
        return _omnipy.invoke(self, "getAllTopLevelTopologicalLinkNames", _0_emsMgr.EMSMgr_I._d_getAllTopLevelTopologicalLinkNames, args)

    def getTopLevelTopologicalLink(self, *args):
        return _omnipy.invoke(self, "getTopLevelTopologicalLink", _0_emsMgr.EMSMgr_I._d_getTopLevelTopologicalLink, args)

    def getAllEMSAndMEActiveAlarms(self, *args):
        return _omnipy.invoke(self, "getAllEMSAndMEActiveAlarms", _0_emsMgr.EMSMgr_I._d_getAllEMSAndMEActiveAlarms, args)

    def getAllEMSSystemActiveAlarms(self, *args):
        return _omnipy.invoke(self, "getAllEMSSystemActiveAlarms", _0_emsMgr.EMSMgr_I._d_getAllEMSSystemActiveAlarms, args)

    def getObjectRootAlarms(self, *args):
        return _omnipy.invoke(self, "getObjectRootAlarms", _0_emsMgr.EMSMgr_I._d_getObjectRootAlarms, args)

    def getObjectClockSourceStatus(self, *args):
        return _omnipy.invoke(self, "getObjectClockSourceStatus", _0_emsMgr.EMSMgr_I._d_getObjectClockSourceStatus, args)

    def acknowledgeAlarms(self, *args):
        return _omnipy.invoke(self, "acknowledgeAlarms", _0_emsMgr.EMSMgr_I._d_acknowledgeAlarms, args)

    def unacknowledgeAlarms(self, *args):
        return _omnipy.invoke(self, "unacknowledgeAlarms", _0_emsMgr.EMSMgr_I._d_unacknowledgeAlarms, args)

    __methods__ = ["getEMS", "getAllTopLevelSubnetworks", "getAllTopLevelSubnetworkNames", "getAllTopLevelTopologicalLinks", "getAllTopLevelTopologicalLinkNames", "getTopLevelTopologicalLink", "getAllEMSAndMEActiveAlarms", "getAllEMSSystemActiveAlarms", "getObjectRootAlarms", "getObjectClockSourceStatus", "acknowledgeAlarms", "unacknowledgeAlarms"] + _0_common._objref_Common_I.__methods__

omniORB.registerObjref(EMSMgr_I._NP_RepositoryId, _objref_EMSMgr_I)
_0_emsMgr._objref_EMSMgr_I = _objref_EMSMgr_I
del EMSMgr_I, _objref_EMSMgr_I

# EMSMgr_I skeleton
__name__ = "emsMgr__POA"
class EMSMgr_I (_0_common__POA.Common_I):
    _NP_RepositoryId = _0_emsMgr.EMSMgr_I._NP_RepositoryId


    _omni_op_d = {"getEMS": _0_emsMgr.EMSMgr_I._d_getEMS, "getAllTopLevelSubnetworks": _0_emsMgr.EMSMgr_I._d_getAllTopLevelSubnetworks, "getAllTopLevelSubnetworkNames": _0_emsMgr.EMSMgr_I._d_getAllTopLevelSubnetworkNames, "getAllTopLevelTopologicalLinks": _0_emsMgr.EMSMgr_I._d_getAllTopLevelTopologicalLinks, "getAllTopLevelTopologicalLinkNames": _0_emsMgr.EMSMgr_I._d_getAllTopLevelTopologicalLinkNames, "getTopLevelTopologicalLink": _0_emsMgr.EMSMgr_I._d_getTopLevelTopologicalLink, "getAllEMSAndMEActiveAlarms": _0_emsMgr.EMSMgr_I._d_getAllEMSAndMEActiveAlarms, "getAllEMSSystemActiveAlarms": _0_emsMgr.EMSMgr_I._d_getAllEMSSystemActiveAlarms, "getObjectRootAlarms": _0_emsMgr.EMSMgr_I._d_getObjectRootAlarms, "getObjectClockSourceStatus": _0_emsMgr.EMSMgr_I._d_getObjectClockSourceStatus, "acknowledgeAlarms": _0_emsMgr.EMSMgr_I._d_acknowledgeAlarms, "unacknowledgeAlarms": _0_emsMgr.EMSMgr_I._d_unacknowledgeAlarms}
    _omni_op_d.update(_0_common__POA.Common_I._omni_op_d)

EMSMgr_I._omni_skeleton = EMSMgr_I
_0_emsMgr__POA.EMSMgr_I = EMSMgr_I
omniORB.registerSkeleton(EMSMgr_I._NP_RepositoryId, EMSMgr_I)
del EMSMgr_I
__name__ = "emsMgr"

#
# End of module "emsMgr"
#
__name__ = "emsMgr_idl"

_exported_modules = ( "emsMgr", )

# The end.
