# Python stubs generated by omniidl from protection.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)

# #include "globaldefs.idl"
import globaldefs_idl
_0_globaldefs = omniORB.openModule("globaldefs")
_0_globaldefs__POA = omniORB.openModule("globaldefs__POA")
# #include "transmissionParameters.idl"
import transmissionParameters_idl
_0_transmissionParameters = omniORB.openModule("transmissionParameters")
_0_transmissionParameters__POA = omniORB.openModule("transmissionParameters__POA")
# #include "common.idl"
import common_idl
_0_common = omniORB.openModule("common")
_0_common__POA = omniORB.openModule("common__POA")

#
# Start of module "protection"
#
__name__ = "protection"
_0_protection = omniORB.openModule("protection", r"protection.idl")
_0_protection__POA = omniORB.openModule("protection__POA", r"protection.idl")


# enum ProtectionSchemeState_T
_0_protection.PSS_UNKNOWN = omniORB.EnumItem("PSS_UNKNOWN", 0)
_0_protection.PSS_AUTOMATIC = omniORB.EnumItem("PSS_AUTOMATIC", 1)
_0_protection.PSS_FORCED_OR_LOCKED_OUT = omniORB.EnumItem("PSS_FORCED_OR_LOCKED_OUT", 2)
_0_protection.ProtectionSchemeState_T = omniORB.Enum("IDL:mtnm.tmforum.org/protection/ProtectionSchemeState_T:1.0", (_0_protection.PSS_UNKNOWN, _0_protection.PSS_AUTOMATIC, _0_protection.PSS_FORCED_OR_LOCKED_OUT,))

_0_protection._d_ProtectionSchemeState_T  = (omniORB.tcInternal.tv_enum, _0_protection.ProtectionSchemeState_T._NP_RepositoryId, "ProtectionSchemeState_T", _0_protection.ProtectionSchemeState_T._items)
_0_protection._tc_ProtectionSchemeState_T = omniORB.tcInternal.createTypeCode(_0_protection._d_ProtectionSchemeState_T)
omniORB.registerType(_0_protection.ProtectionSchemeState_T._NP_RepositoryId, _0_protection._d_ProtectionSchemeState_T, _0_protection._tc_ProtectionSchemeState_T)

# enum ProtectionType_T
_0_protection.PT_MSP_APS = omniORB.EnumItem("PT_MSP_APS", 0)
_0_protection.PT_SNCP = omniORB.EnumItem("PT_SNCP", 1)
_0_protection.ProtectionType_T = omniORB.Enum("IDL:mtnm.tmforum.org/protection/ProtectionType_T:1.0", (_0_protection.PT_MSP_APS, _0_protection.PT_SNCP,))

_0_protection._d_ProtectionType_T  = (omniORB.tcInternal.tv_enum, _0_protection.ProtectionType_T._NP_RepositoryId, "ProtectionType_T", _0_protection.ProtectionType_T._items)
_0_protection._tc_ProtectionType_T = omniORB.tcInternal.createTypeCode(_0_protection._d_ProtectionType_T)
omniORB.registerType(_0_protection.ProtectionType_T._NP_RepositoryId, _0_protection._d_ProtectionType_T, _0_protection._tc_ProtectionType_T)

# enum SwitchReason_T
_0_protection.SR_NA = omniORB.EnumItem("SR_NA", 0)
_0_protection.SR_RESTORED = omniORB.EnumItem("SR_RESTORED", 1)
_0_protection.SR_SIGNAL_FAIL = omniORB.EnumItem("SR_SIGNAL_FAIL", 2)
_0_protection.SR_SIGNAL_MISMATCH = omniORB.EnumItem("SR_SIGNAL_MISMATCH", 3)
_0_protection.SR_SIGNAL_DEGRADE = omniORB.EnumItem("SR_SIGNAL_DEGRADE", 4)
_0_protection.SR_AUTOMATIC_SWITCH = omniORB.EnumItem("SR_AUTOMATIC_SWITCH", 5)
_0_protection.SR_MANUAL = omniORB.EnumItem("SR_MANUAL", 6)
_0_protection.SwitchReason_T = omniORB.Enum("IDL:mtnm.tmforum.org/protection/SwitchReason_T:1.0", (_0_protection.SR_NA, _0_protection.SR_RESTORED, _0_protection.SR_SIGNAL_FAIL, _0_protection.SR_SIGNAL_MISMATCH, _0_protection.SR_SIGNAL_DEGRADE, _0_protection.SR_AUTOMATIC_SWITCH, _0_protection.SR_MANUAL,))

_0_protection._d_SwitchReason_T  = (omniORB.tcInternal.tv_enum, _0_protection.SwitchReason_T._NP_RepositoryId, "SwitchReason_T", _0_protection.SwitchReason_T._items)
_0_protection._tc_SwitchReason_T = omniORB.tcInternal.createTypeCode(_0_protection._d_SwitchReason_T)
omniORB.registerType(_0_protection.SwitchReason_T._NP_RepositoryId, _0_protection._d_SwitchReason_T, _0_protection._tc_SwitchReason_T)

# typedef ... ESwitchReason_T
class ESwitchReason_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/ESwitchReason_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_protection.ESwitchReason_T = ESwitchReason_T
_0_protection._d_ESwitchReason_T  = (omniORB.tcInternal.tv_string,0)
_0_protection._ad_ESwitchReason_T = (omniORB.tcInternal.tv_alias, ESwitchReason_T._NP_RepositoryId, "ESwitchReason_T", (omniORB.tcInternal.tv_string,0))
_0_protection._tc_ESwitchReason_T = omniORB.tcInternal.createTypeCode(_0_protection._ad_ESwitchReason_T)
omniORB.registerType(ESwitchReason_T._NP_RepositoryId, _0_protection._ad_ESwitchReason_T, _0_protection._tc_ESwitchReason_T)
del ESwitchReason_T

# enum ProtectionCommand_T
_0_protection.PC_CLEAR = omniORB.EnumItem("PC_CLEAR", 0)
_0_protection.PC_LOCKOUT = omniORB.EnumItem("PC_LOCKOUT", 1)
_0_protection.PC_FORCED_SWITCH = omniORB.EnumItem("PC_FORCED_SWITCH", 2)
_0_protection.PC_MANUAL_SWITCH = omniORB.EnumItem("PC_MANUAL_SWITCH", 3)
_0_protection.PC_EXERCISER = omniORB.EnumItem("PC_EXERCISER", 4)
_0_protection.ProtectionCommand_T = omniORB.Enum("IDL:mtnm.tmforum.org/protection/ProtectionCommand_T:1.0", (_0_protection.PC_CLEAR, _0_protection.PC_LOCKOUT, _0_protection.PC_FORCED_SWITCH, _0_protection.PC_MANUAL_SWITCH, _0_protection.PC_EXERCISER,))

_0_protection._d_ProtectionCommand_T  = (omniORB.tcInternal.tv_enum, _0_protection.ProtectionCommand_T._NP_RepositoryId, "ProtectionCommand_T", _0_protection.ProtectionCommand_T._items)
_0_protection._tc_ProtectionCommand_T = omniORB.tcInternal.createTypeCode(_0_protection._d_ProtectionCommand_T)
omniORB.registerType(_0_protection.ProtectionCommand_T._NP_RepositoryId, _0_protection._d_ProtectionCommand_T, _0_protection._tc_ProtectionCommand_T)

# enum ProtectionGroupType_T
_0_protection.PGT_MSP_1_PLUS_1 = omniORB.EnumItem("PGT_MSP_1_PLUS_1", 0)
_0_protection.PGT_MSP_1_FOR_N = omniORB.EnumItem("PGT_MSP_1_FOR_N", 1)
_0_protection.PGT_2_FIBER_BLSR = omniORB.EnumItem("PGT_2_FIBER_BLSR", 2)
_0_protection.PGT_4_FIBER_BLSR = omniORB.EnumItem("PGT_4_FIBER_BLSR", 3)
_0_protection.ProtectionGroupType_T = omniORB.Enum("IDL:mtnm.tmforum.org/protection/ProtectionGroupType_T:1.0", (_0_protection.PGT_MSP_1_PLUS_1, _0_protection.PGT_MSP_1_FOR_N, _0_protection.PGT_2_FIBER_BLSR, _0_protection.PGT_4_FIBER_BLSR,))

_0_protection._d_ProtectionGroupType_T  = (omniORB.tcInternal.tv_enum, _0_protection.ProtectionGroupType_T._NP_RepositoryId, "ProtectionGroupType_T", _0_protection.ProtectionGroupType_T._items)
_0_protection._tc_ProtectionGroupType_T = omniORB.tcInternal.createTypeCode(_0_protection._d_ProtectionGroupType_T)
omniORB.registerType(_0_protection.ProtectionGroupType_T._NP_RepositoryId, _0_protection._d_ProtectionGroupType_T, _0_protection._tc_ProtectionGroupType_T)

# enum ReversionMode_T
_0_protection.RM_UNKNOWN = omniORB.EnumItem("RM_UNKNOWN", 0)
_0_protection.RM_NON_REVERTIVE = omniORB.EnumItem("RM_NON_REVERTIVE", 1)
_0_protection.RM_REVERTIVE = omniORB.EnumItem("RM_REVERTIVE", 2)
_0_protection.ReversionMode_T = omniORB.Enum("IDL:mtnm.tmforum.org/protection/ReversionMode_T:1.0", (_0_protection.RM_UNKNOWN, _0_protection.RM_NON_REVERTIVE, _0_protection.RM_REVERTIVE,))

_0_protection._d_ReversionMode_T  = (omniORB.tcInternal.tv_enum, _0_protection.ReversionMode_T._NP_RepositoryId, "ReversionMode_T", _0_protection.ReversionMode_T._items)
_0_protection._tc_ReversionMode_T = omniORB.tcInternal.createTypeCode(_0_protection._d_ReversionMode_T)
omniORB.registerType(_0_protection.ReversionMode_T._NP_RepositoryId, _0_protection._d_ReversionMode_T, _0_protection._tc_ReversionMode_T)

# struct ProtectionGroup_T
_0_protection.ProtectionGroup_T = omniORB.newEmptyClass()
class ProtectionGroup_T (omniORB.StructBase):
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/ProtectionGroup_T:1.0"

    def __init__(self, name, userLabel, nativeEMSName, owner, protectionGroupType, protectionSchemeState, reversionMode, rate, pgpTPList, pgpParameters, additionalInfo):
        self.name = name
        self.userLabel = userLabel
        self.nativeEMSName = nativeEMSName
        self.owner = owner
        self.protectionGroupType = protectionGroupType
        self.protectionSchemeState = protectionSchemeState
        self.reversionMode = reversionMode
        self.rate = rate
        self.pgpTPList = pgpTPList
        self.pgpParameters = pgpParameters
        self.additionalInfo = additionalInfo

_0_protection.ProtectionGroup_T = ProtectionGroup_T
_0_protection._d_ProtectionGroup_T  = (omniORB.tcInternal.tv_struct, ProtectionGroup_T, ProtectionGroup_T._NP_RepositoryId, "ProtectionGroup_T", "name", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "userLabel", (omniORB.tcInternal.tv_string,0), "nativeEMSName", (omniORB.tcInternal.tv_string,0), "owner", (omniORB.tcInternal.tv_string,0), "protectionGroupType", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionGroupType_T:1.0"], "protectionSchemeState", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionSchemeState_T:1.0"], "reversionMode", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ReversionMode_T:1.0"], "rate", omniORB.typeMapping["IDL:mtnm.tmforum.org/transmissionParameters/LayerRate_T:1.0"], "pgpTPList", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributesList_T:1.0"], "pgpParameters", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0"], "additionalInfo", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0"])
_0_protection._tc_ProtectionGroup_T = omniORB.tcInternal.createTypeCode(_0_protection._d_ProtectionGroup_T)
omniORB.registerType(ProtectionGroup_T._NP_RepositoryId, _0_protection._d_ProtectionGroup_T, _0_protection._tc_ProtectionGroup_T)
del ProtectionGroup_T

# typedef ... ProtectionGroupList_T
class ProtectionGroupList_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/ProtectionGroupList_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_protection.ProtectionGroupList_T = ProtectionGroupList_T
_0_protection._d_ProtectionGroupList_T  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionGroup_T:1.0"], 0)
_0_protection._ad_ProtectionGroupList_T = (omniORB.tcInternal.tv_alias, ProtectionGroupList_T._NP_RepositoryId, "ProtectionGroupList_T", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionGroup_T:1.0"], 0))
_0_protection._tc_ProtectionGroupList_T = omniORB.tcInternal.createTypeCode(_0_protection._ad_ProtectionGroupList_T)
omniORB.registerType(ProtectionGroupList_T._NP_RepositoryId, _0_protection._ad_ProtectionGroupList_T, _0_protection._tc_ProtectionGroupList_T)
del ProtectionGroupList_T

# struct SwitchData_T
_0_protection.SwitchData_T = omniORB.newEmptyClass()
class SwitchData_T (omniORB.StructBase):
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/SwitchData_T:1.0"

    def __init__(self, protectionType, switchReason, layerRate, groupName, protectedTP, switchToTP, additionalInfo):
        self.protectionType = protectionType
        self.switchReason = switchReason
        self.layerRate = layerRate
        self.groupName = groupName
        self.protectedTP = protectedTP
        self.switchToTP = switchToTP
        self.additionalInfo = additionalInfo

_0_protection.SwitchData_T = SwitchData_T
_0_protection._d_SwitchData_T  = (omniORB.tcInternal.tv_struct, SwitchData_T, SwitchData_T._NP_RepositoryId, "SwitchData_T", "protectionType", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionType_T:1.0"], "switchReason", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/SwitchReason_T:1.0"], "layerRate", omniORB.typeMapping["IDL:mtnm.tmforum.org/transmissionParameters/LayerRate_T:1.0"], "groupName", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "protectedTP", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "switchToTP", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "additionalInfo", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0"])
_0_protection._tc_SwitchData_T = omniORB.tcInternal.createTypeCode(_0_protection._d_SwitchData_T)
omniORB.registerType(SwitchData_T._NP_RepositoryId, _0_protection._d_SwitchData_T, _0_protection._tc_SwitchData_T)
del SwitchData_T

# typedef ... SwitchDataList_T
class SwitchDataList_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/SwitchDataList_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_protection.SwitchDataList_T = SwitchDataList_T
_0_protection._d_SwitchDataList_T  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/SwitchData_T:1.0"], 0)
_0_protection._ad_SwitchDataList_T = (omniORB.tcInternal.tv_alias, SwitchDataList_T._NP_RepositoryId, "SwitchDataList_T", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/SwitchData_T:1.0"], 0))
_0_protection._tc_SwitchDataList_T = omniORB.tcInternal.createTypeCode(_0_protection._ad_SwitchDataList_T)
omniORB.registerType(SwitchDataList_T._NP_RepositoryId, _0_protection._ad_SwitchDataList_T, _0_protection._tc_SwitchDataList_T)
del SwitchDataList_T

# enum ProtectionSubnetworkType_T
_0_protection.PSNT_MSP_1_PLUS_1 = omniORB.EnumItem("PSNT_MSP_1_PLUS_1", 0)
_0_protection.PSNT_MSP_M_FOR_N = omniORB.EnumItem("PSNT_MSP_M_FOR_N", 1)
_0_protection.PSNT_2_FIBER_ULSR = omniORB.EnumItem("PSNT_2_FIBER_ULSR", 2)
_0_protection.PSNT_2_FIBER_BLSR = omniORB.EnumItem("PSNT_2_FIBER_BLSR", 3)
_0_protection.PSNT_4_FIBER_BLSR = omniORB.EnumItem("PSNT_4_FIBER_BLSR", 4)
_0_protection.PSNT_USNCP = omniORB.EnumItem("PSNT_USNCP", 5)
_0_protection.PSNT_BSNCP = omniORB.EnumItem("PSNT_BSNCP", 6)
_0_protection.PSNT_UPP = omniORB.EnumItem("PSNT_UPP", 7)
_0_protection.PSNT_BPP = omniORB.EnumItem("PSNT_BPP", 8)
_0_protection.PSNT_NP = omniORB.EnumItem("PSNT_NP", 9)
_0_protection.PSNT_SNC_NODE = omniORB.EnumItem("PSNT_SNC_NODE", 10)
_0_protection.ProtectionSubnetworkType_T = omniORB.Enum("IDL:mtnm.tmforum.org/protection/ProtectionSubnetworkType_T:1.0", (_0_protection.PSNT_MSP_1_PLUS_1, _0_protection.PSNT_MSP_M_FOR_N, _0_protection.PSNT_2_FIBER_ULSR, _0_protection.PSNT_2_FIBER_BLSR, _0_protection.PSNT_4_FIBER_BLSR, _0_protection.PSNT_USNCP, _0_protection.PSNT_BSNCP, _0_protection.PSNT_UPP, _0_protection.PSNT_BPP, _0_protection.PSNT_NP, _0_protection.PSNT_SNC_NODE,))

_0_protection._d_ProtectionSubnetworkType_T  = (omniORB.tcInternal.tv_enum, _0_protection.ProtectionSubnetworkType_T._NP_RepositoryId, "ProtectionSubnetworkType_T", _0_protection.ProtectionSubnetworkType_T._items)
_0_protection._tc_ProtectionSubnetworkType_T = omniORB.tcInternal.createTypeCode(_0_protection._d_ProtectionSubnetworkType_T)
omniORB.registerType(_0_protection.ProtectionSubnetworkType_T._NP_RepositoryId, _0_protection._d_ProtectionSubnetworkType_T, _0_protection._tc_ProtectionSubnetworkType_T)

# typedef ... TSSeq_T
class TSSeq_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/TSSeq_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_protection.TSSeq_T = TSSeq_T
_0_protection._d_TSSeq_T  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_ushort, 0)
_0_protection._ad_TSSeq_T = (omniORB.tcInternal.tv_alias, TSSeq_T._NP_RepositoryId, "TSSeq_T", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_ushort, 0))
_0_protection._tc_TSSeq_T = omniORB.tcInternal.createTypeCode(_0_protection._ad_TSSeq_T)
omniORB.registerType(TSSeq_T._NP_RepositoryId, _0_protection._ad_TSSeq_T, _0_protection._tc_TSSeq_T)
del TSSeq_T

# struct ProtectionSubnetworkLink_T
_0_protection.ProtectionSubnetworkLink_T = omniORB.newEmptyClass()
class ProtectionSubnetworkLink_T (omniORB.StructBase):
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/ProtectionSubnetworkLink_T:1.0"

    def __init__(self, srcTP, snkTP, vc4List):
        self.srcTP = srcTP
        self.snkTP = snkTP
        self.vc4List = vc4List

_0_protection.ProtectionSubnetworkLink_T = ProtectionSubnetworkLink_T
_0_protection._d_ProtectionSubnetworkLink_T  = (omniORB.tcInternal.tv_struct, ProtectionSubnetworkLink_T, ProtectionSubnetworkLink_T._NP_RepositoryId, "ProtectionSubnetworkLink_T", "srcTP", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "snkTP", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "vc4List", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/TSSeq_T:1.0"])
_0_protection._tc_ProtectionSubnetworkLink_T = omniORB.tcInternal.createTypeCode(_0_protection._d_ProtectionSubnetworkLink_T)
omniORB.registerType(ProtectionSubnetworkLink_T._NP_RepositoryId, _0_protection._d_ProtectionSubnetworkLink_T, _0_protection._tc_ProtectionSubnetworkLink_T)
del ProtectionSubnetworkLink_T

# typedef ... ProtectionSubnetworkSection_T
class ProtectionSubnetworkSection_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/ProtectionSubnetworkSection_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_protection.ProtectionSubnetworkSection_T = ProtectionSubnetworkSection_T
_0_protection._d_ProtectionSubnetworkSection_T  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionSubnetworkLink_T:1.0"], 0)
_0_protection._ad_ProtectionSubnetworkSection_T = (omniORB.tcInternal.tv_alias, ProtectionSubnetworkSection_T._NP_RepositoryId, "ProtectionSubnetworkSection_T", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionSubnetworkLink_T:1.0"], 0))
_0_protection._tc_ProtectionSubnetworkSection_T = omniORB.tcInternal.createTypeCode(_0_protection._ad_ProtectionSubnetworkSection_T)
omniORB.registerType(ProtectionSubnetworkSection_T._NP_RepositoryId, _0_protection._ad_ProtectionSubnetworkSection_T, _0_protection._tc_ProtectionSubnetworkSection_T)
del ProtectionSubnetworkSection_T

# typedef ... ProtectionSubnetworkCircle_T
class ProtectionSubnetworkCircle_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/ProtectionSubnetworkCircle_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_protection.ProtectionSubnetworkCircle_T = ProtectionSubnetworkCircle_T
_0_protection._d_ProtectionSubnetworkCircle_T  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionSubnetworkSection_T:1.0"], 0)
_0_protection._ad_ProtectionSubnetworkCircle_T = (omniORB.tcInternal.tv_alias, ProtectionSubnetworkCircle_T._NP_RepositoryId, "ProtectionSubnetworkCircle_T", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionSubnetworkSection_T:1.0"], 0))
_0_protection._tc_ProtectionSubnetworkCircle_T = omniORB.tcInternal.createTypeCode(_0_protection._ad_ProtectionSubnetworkCircle_T)
omniORB.registerType(ProtectionSubnetworkCircle_T._NP_RepositoryId, _0_protection._ad_ProtectionSubnetworkCircle_T, _0_protection._tc_ProtectionSubnetworkCircle_T)
del ProtectionSubnetworkCircle_T

# typedef ... NEIDSeq_T
class NEIDSeq_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/NEIDSeq_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_protection.NEIDSeq_T = NEIDSeq_T
_0_protection._d_NEIDSeq_T  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_ulong, 0)
_0_protection._ad_NEIDSeq_T = (omniORB.tcInternal.tv_alias, NEIDSeq_T._NP_RepositoryId, "NEIDSeq_T", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_ulong, 0))
_0_protection._tc_NEIDSeq_T = omniORB.tcInternal.createTypeCode(_0_protection._ad_NEIDSeq_T)
omniORB.registerType(NEIDSeq_T._NP_RepositoryId, _0_protection._ad_NEIDSeq_T, _0_protection._tc_NEIDSeq_T)
del NEIDSeq_T

# struct ProtectionSubnetwork_T
_0_protection.ProtectionSubnetwork_T = omniORB.newEmptyClass()
class ProtectionSubnetwork_T (omniORB.StructBase):
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/ProtectionSubnetwork_T:1.0"

    def __init__(self, name, userLabel, nativeEMSName, owner, layerRate, psnType, neIDList, psnLinks, additionalInfo):
        self.name = name
        self.userLabel = userLabel
        self.nativeEMSName = nativeEMSName
        self.owner = owner
        self.layerRate = layerRate
        self.psnType = psnType
        self.neIDList = neIDList
        self.psnLinks = psnLinks
        self.additionalInfo = additionalInfo

_0_protection.ProtectionSubnetwork_T = ProtectionSubnetwork_T
_0_protection._d_ProtectionSubnetwork_T  = (omniORB.tcInternal.tv_struct, ProtectionSubnetwork_T, ProtectionSubnetwork_T._NP_RepositoryId, "ProtectionSubnetwork_T", "name", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "userLabel", (omniORB.tcInternal.tv_string,0), "nativeEMSName", (omniORB.tcInternal.tv_string,0), "owner", (omniORB.tcInternal.tv_string,0), "layerRate", omniORB.typeMapping["IDL:mtnm.tmforum.org/transmissionParameters/LayerRate_T:1.0"], "psnType", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionSubnetworkType_T:1.0"], "neIDList", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/NEIDSeq_T:1.0"], "psnLinks", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionSubnetworkCircle_T:1.0"], "additionalInfo", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0"])
_0_protection._tc_ProtectionSubnetwork_T = omniORB.tcInternal.createTypeCode(_0_protection._d_ProtectionSubnetwork_T)
omniORB.registerType(ProtectionSubnetwork_T._NP_RepositoryId, _0_protection._d_ProtectionSubnetwork_T, _0_protection._tc_ProtectionSubnetwork_T)
del ProtectionSubnetwork_T

# typedef ... ProtectionSubnetworkList_T
class ProtectionSubnetworkList_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/ProtectionSubnetworkList_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_protection.ProtectionSubnetworkList_T = ProtectionSubnetworkList_T
_0_protection._d_ProtectionSubnetworkList_T  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionSubnetwork_T:1.0"], 0)
_0_protection._ad_ProtectionSubnetworkList_T = (omniORB.tcInternal.tv_alias, ProtectionSubnetworkList_T._NP_RepositoryId, "ProtectionSubnetworkList_T", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionSubnetwork_T:1.0"], 0))
_0_protection._tc_ProtectionSubnetworkList_T = omniORB.tcInternal.createTypeCode(_0_protection._ad_ProtectionSubnetworkList_T)
omniORB.registerType(ProtectionSubnetworkList_T._NP_RepositoryId, _0_protection._ad_ProtectionSubnetworkList_T, _0_protection._tc_ProtectionSubnetworkList_T)
del ProtectionSubnetworkList_T

# typedef ... WDMProtectionGroupType_T
class WDMProtectionGroupType_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/WDMProtectionGroupType_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_protection.WDMProtectionGroupType_T = WDMProtectionGroupType_T
_0_protection._d_WDMProtectionGroupType_T  = (omniORB.tcInternal.tv_string,0)
_0_protection._ad_WDMProtectionGroupType_T = (omniORB.tcInternal.tv_alias, WDMProtectionGroupType_T._NP_RepositoryId, "WDMProtectionGroupType_T", (omniORB.tcInternal.tv_string,0))
_0_protection._tc_WDMProtectionGroupType_T = omniORB.tcInternal.createTypeCode(_0_protection._ad_WDMProtectionGroupType_T)
omniORB.registerType(WDMProtectionGroupType_T._NP_RepositoryId, _0_protection._ad_WDMProtectionGroupType_T, _0_protection._tc_WDMProtectionGroupType_T)
del WDMProtectionGroupType_T

# struct WDMProtectionGroup_T
_0_protection.WDMProtectionGroup_T = omniORB.newEmptyClass()
class WDMProtectionGroup_T (omniORB.StructBase):
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/WDMProtectionGroup_T:1.0"

    def __init__(self, name, userLabel, nativeEMSName, owner, protectionGroupType, protectionSchemeState, reversionMode, pgpTPList, pgpParameters, additionalInfo):
        self.name = name
        self.userLabel = userLabel
        self.nativeEMSName = nativeEMSName
        self.owner = owner
        self.protectionGroupType = protectionGroupType
        self.protectionSchemeState = protectionSchemeState
        self.reversionMode = reversionMode
        self.pgpTPList = pgpTPList
        self.pgpParameters = pgpParameters
        self.additionalInfo = additionalInfo

_0_protection.WDMProtectionGroup_T = WDMProtectionGroup_T
_0_protection._d_WDMProtectionGroup_T  = (omniORB.tcInternal.tv_struct, WDMProtectionGroup_T, WDMProtectionGroup_T._NP_RepositoryId, "WDMProtectionGroup_T", "name", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "userLabel", (omniORB.tcInternal.tv_string,0), "nativeEMSName", (omniORB.tcInternal.tv_string,0), "owner", (omniORB.tcInternal.tv_string,0), "protectionGroupType", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/WDMProtectionGroupType_T:1.0"], "protectionSchemeState", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionSchemeState_T:1.0"], "reversionMode", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ReversionMode_T:1.0"], "pgpTPList", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributesList_T:1.0"], "pgpParameters", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0"], "additionalInfo", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0"])
_0_protection._tc_WDMProtectionGroup_T = omniORB.tcInternal.createTypeCode(_0_protection._d_WDMProtectionGroup_T)
omniORB.registerType(WDMProtectionGroup_T._NP_RepositoryId, _0_protection._d_WDMProtectionGroup_T, _0_protection._tc_WDMProtectionGroup_T)
del WDMProtectionGroup_T

# typedef ... WDMProtectionGroupList_T
class WDMProtectionGroupList_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/WDMProtectionGroupList_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_protection.WDMProtectionGroupList_T = WDMProtectionGroupList_T
_0_protection._d_WDMProtectionGroupList_T  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/WDMProtectionGroup_T:1.0"], 0)
_0_protection._ad_WDMProtectionGroupList_T = (omniORB.tcInternal.tv_alias, WDMProtectionGroupList_T._NP_RepositoryId, "WDMProtectionGroupList_T", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/WDMProtectionGroup_T:1.0"], 0))
_0_protection._tc_WDMProtectionGroupList_T = omniORB.tcInternal.createTypeCode(_0_protection._ad_WDMProtectionGroupList_T)
omniORB.registerType(WDMProtectionGroupList_T._NP_RepositoryId, _0_protection._ad_WDMProtectionGroupList_T, _0_protection._tc_WDMProtectionGroupList_T)
del WDMProtectionGroupList_T

# struct WDMSwitchData_T
_0_protection.WDMSwitchData_T = omniORB.newEmptyClass()
class WDMSwitchData_T (omniORB.StructBase):
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/WDMSwitchData_T:1.0"

    def __init__(self, protectionType, switchReason, wPGPName, protectedTP, switchToTP, additionalInfo):
        self.protectionType = protectionType
        self.switchReason = switchReason
        self.wPGPName = wPGPName
        self.protectedTP = protectedTP
        self.switchToTP = switchToTP
        self.additionalInfo = additionalInfo

_0_protection.WDMSwitchData_T = WDMSwitchData_T
_0_protection._d_WDMSwitchData_T  = (omniORB.tcInternal.tv_struct, WDMSwitchData_T, WDMSwitchData_T._NP_RepositoryId, "WDMSwitchData_T", "protectionType", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/WDMProtectionGroupType_T:1.0"], "switchReason", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/SwitchReason_T:1.0"], "wPGPName", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "protectedTP", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "switchToTP", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "additionalInfo", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0"])
_0_protection._tc_WDMSwitchData_T = omniORB.tcInternal.createTypeCode(_0_protection._d_WDMSwitchData_T)
omniORB.registerType(WDMSwitchData_T._NP_RepositoryId, _0_protection._d_WDMSwitchData_T, _0_protection._tc_WDMSwitchData_T)
del WDMSwitchData_T

# typedef ... WDMSwitchDataList_T
class WDMSwitchDataList_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/WDMSwitchDataList_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_protection.WDMSwitchDataList_T = WDMSwitchDataList_T
_0_protection._d_WDMSwitchDataList_T  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/WDMSwitchData_T:1.0"], 0)
_0_protection._ad_WDMSwitchDataList_T = (omniORB.tcInternal.tv_alias, WDMSwitchDataList_T._NP_RepositoryId, "WDMSwitchDataList_T", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/WDMSwitchData_T:1.0"], 0))
_0_protection._tc_WDMSwitchDataList_T = omniORB.tcInternal.createTypeCode(_0_protection._ad_WDMSwitchDataList_T)
omniORB.registerType(WDMSwitchDataList_T._NP_RepositoryId, _0_protection._ad_WDMSwitchDataList_T, _0_protection._tc_WDMSwitchDataList_T)
del WDMSwitchDataList_T

# typedef ... EProtectionGroupType_T
class EProtectionGroupType_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/EProtectionGroupType_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_protection.EProtectionGroupType_T = EProtectionGroupType_T
_0_protection._d_EProtectionGroupType_T  = (omniORB.tcInternal.tv_string,0)
_0_protection._ad_EProtectionGroupType_T = (omniORB.tcInternal.tv_alias, EProtectionGroupType_T._NP_RepositoryId, "EProtectionGroupType_T", (omniORB.tcInternal.tv_string,0))
_0_protection._tc_EProtectionGroupType_T = omniORB.tcInternal.createTypeCode(_0_protection._ad_EProtectionGroupType_T)
omniORB.registerType(EProtectionGroupType_T._NP_RepositoryId, _0_protection._ad_EProtectionGroupType_T, _0_protection._tc_EProtectionGroupType_T)
del EProtectionGroupType_T

# struct EProtectionGroup_T
_0_protection.EProtectionGroup_T = omniORB.newEmptyClass()
class EProtectionGroup_T (omniORB.StructBase):
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/EProtectionGroup_T:1.0"

    def __init__(self, name, userLabel, nativeEMSName, owner, eProtectionGroupType, protectionSchemeState, reversionMode, protectedList, protectingList, ePgpParameters, additionalInfo):
        self.name = name
        self.userLabel = userLabel
        self.nativeEMSName = nativeEMSName
        self.owner = owner
        self.eProtectionGroupType = eProtectionGroupType
        self.protectionSchemeState = protectionSchemeState
        self.reversionMode = reversionMode
        self.protectedList = protectedList
        self.protectingList = protectingList
        self.ePgpParameters = ePgpParameters
        self.additionalInfo = additionalInfo

_0_protection.EProtectionGroup_T = EProtectionGroup_T
_0_protection._d_EProtectionGroup_T  = (omniORB.tcInternal.tv_struct, EProtectionGroup_T, EProtectionGroup_T._NP_RepositoryId, "EProtectionGroup_T", "name", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "userLabel", (omniORB.tcInternal.tv_string,0), "nativeEMSName", (omniORB.tcInternal.tv_string,0), "owner", (omniORB.tcInternal.tv_string,0), "eProtectionGroupType", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/EProtectionGroupType_T:1.0"], "protectionSchemeState", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionSchemeState_T:1.0"], "reversionMode", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ReversionMode_T:1.0"], "protectedList", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributesList_T:1.0"], "protectingList", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributesList_T:1.0"], "ePgpParameters", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0"], "additionalInfo", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0"])
_0_protection._tc_EProtectionGroup_T = omniORB.tcInternal.createTypeCode(_0_protection._d_EProtectionGroup_T)
omniORB.registerType(EProtectionGroup_T._NP_RepositoryId, _0_protection._d_EProtectionGroup_T, _0_protection._tc_EProtectionGroup_T)
del EProtectionGroup_T

# typedef ... EProtectionGroupList_T
class EProtectionGroupList_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/EProtectionGroupList_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_protection.EProtectionGroupList_T = EProtectionGroupList_T
_0_protection._d_EProtectionGroupList_T  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/EProtectionGroup_T:1.0"], 0)
_0_protection._ad_EProtectionGroupList_T = (omniORB.tcInternal.tv_alias, EProtectionGroupList_T._NP_RepositoryId, "EProtectionGroupList_T", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/EProtectionGroup_T:1.0"], 0))
_0_protection._tc_EProtectionGroupList_T = omniORB.tcInternal.createTypeCode(_0_protection._ad_EProtectionGroupList_T)
omniORB.registerType(EProtectionGroupList_T._NP_RepositoryId, _0_protection._ad_EProtectionGroupList_T, _0_protection._tc_EProtectionGroupList_T)
del EProtectionGroupList_T

# struct ESwitchData_T
_0_protection.ESwitchData_T = omniORB.newEmptyClass()
class ESwitchData_T (omniORB.StructBase):
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/ESwitchData_T:1.0"

    def __init__(self, eProtectionGroupType, eSwitchReason, ePGPName, protectedE, switchToE, additionalInfo):
        self.eProtectionGroupType = eProtectionGroupType
        self.eSwitchReason = eSwitchReason
        self.ePGPName = ePGPName
        self.protectedE = protectedE
        self.switchToE = switchToE
        self.additionalInfo = additionalInfo

_0_protection.ESwitchData_T = ESwitchData_T
_0_protection._d_ESwitchData_T  = (omniORB.tcInternal.tv_struct, ESwitchData_T, ESwitchData_T._NP_RepositoryId, "ESwitchData_T", "eProtectionGroupType", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/EProtectionGroupType_T:1.0"], "eSwitchReason", omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ESwitchReason_T:1.0"], "ePGPName", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "protectedE", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "switchToE", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "additionalInfo", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0"])
_0_protection._tc_ESwitchData_T = omniORB.tcInternal.createTypeCode(_0_protection._d_ESwitchData_T)
omniORB.registerType(ESwitchData_T._NP_RepositoryId, _0_protection._d_ESwitchData_T, _0_protection._tc_ESwitchData_T)
del ESwitchData_T

# typedef ... ESwitchDataList_T
class ESwitchDataList_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/protection/ESwitchDataList_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_protection.ESwitchDataList_T = ESwitchDataList_T
_0_protection._d_ESwitchDataList_T  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ESwitchData_T:1.0"], 0)
_0_protection._ad_ESwitchDataList_T = (omniORB.tcInternal.tv_alias, ESwitchDataList_T._NP_RepositoryId, "ESwitchDataList_T", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ESwitchData_T:1.0"], 0))
_0_protection._tc_ESwitchDataList_T = omniORB.tcInternal.createTypeCode(_0_protection._ad_ESwitchDataList_T)
omniORB.registerType(ESwitchDataList_T._NP_RepositoryId, _0_protection._ad_ESwitchDataList_T, _0_protection._tc_ESwitchDataList_T)
del ESwitchDataList_T

# interface EProtectionGroupIterator_I
_0_protection._d_EProtectionGroupIterator_I = (omniORB.tcInternal.tv_objref, "IDL:mtnm.tmforum.org/protection/EProtectionGroupIterator_I:1.0", "EProtectionGroupIterator_I")
omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/EProtectionGroupIterator_I:1.0"] = _0_protection._d_EProtectionGroupIterator_I
_0_protection.EProtectionGroupIterator_I = omniORB.newEmptyClass()
class EProtectionGroupIterator_I :
    _NP_RepositoryId = _0_protection._d_EProtectionGroupIterator_I[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_protection.EProtectionGroupIterator_I = EProtectionGroupIterator_I
_0_protection._tc_EProtectionGroupIterator_I = omniORB.tcInternal.createTypeCode(_0_protection._d_EProtectionGroupIterator_I)
omniORB.registerType(EProtectionGroupIterator_I._NP_RepositoryId, _0_protection._d_EProtectionGroupIterator_I, _0_protection._tc_EProtectionGroupIterator_I)

# EProtectionGroupIterator_I operations and attributes
EProtectionGroupIterator_I._d_next_n = ((omniORB.tcInternal.tv_ulong, ), (omniORB.tcInternal.tv_boolean, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/EProtectionGroupList_T:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
EProtectionGroupIterator_I._d_getLength = ((), (omniORB.tcInternal.tv_ulong, ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
EProtectionGroupIterator_I._d_destroy = ((), (), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})

# EProtectionGroupIterator_I object reference
class _objref_EProtectionGroupIterator_I (CORBA.Object):
    _NP_RepositoryId = EProtectionGroupIterator_I._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def next_n(self, *args):
        return _omnipy.invoke(self, "next_n", _0_protection.EProtectionGroupIterator_I._d_next_n, args)

    def getLength(self, *args):
        return _omnipy.invoke(self, "getLength", _0_protection.EProtectionGroupIterator_I._d_getLength, args)

    def destroy(self, *args):
        return _omnipy.invoke(self, "destroy", _0_protection.EProtectionGroupIterator_I._d_destroy, args)

    __methods__ = ["next_n", "getLength", "destroy"] + CORBA.Object.__methods__

omniORB.registerObjref(EProtectionGroupIterator_I._NP_RepositoryId, _objref_EProtectionGroupIterator_I)
_0_protection._objref_EProtectionGroupIterator_I = _objref_EProtectionGroupIterator_I
del EProtectionGroupIterator_I, _objref_EProtectionGroupIterator_I

# EProtectionGroupIterator_I skeleton
__name__ = "protection__POA"
class EProtectionGroupIterator_I (PortableServer.Servant):
    _NP_RepositoryId = _0_protection.EProtectionGroupIterator_I._NP_RepositoryId


    _omni_op_d = {"next_n": _0_protection.EProtectionGroupIterator_I._d_next_n, "getLength": _0_protection.EProtectionGroupIterator_I._d_getLength, "destroy": _0_protection.EProtectionGroupIterator_I._d_destroy}

EProtectionGroupIterator_I._omni_skeleton = EProtectionGroupIterator_I
_0_protection__POA.EProtectionGroupIterator_I = EProtectionGroupIterator_I
omniORB.registerSkeleton(EProtectionGroupIterator_I._NP_RepositoryId, EProtectionGroupIterator_I)
del EProtectionGroupIterator_I
__name__ = "protection"

# interface ProtectionGroupIterator_I
_0_protection._d_ProtectionGroupIterator_I = (omniORB.tcInternal.tv_objref, "IDL:mtnm.tmforum.org/protection/ProtectionGroupIterator_I:1.0", "ProtectionGroupIterator_I")
omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionGroupIterator_I:1.0"] = _0_protection._d_ProtectionGroupIterator_I
_0_protection.ProtectionGroupIterator_I = omniORB.newEmptyClass()
class ProtectionGroupIterator_I :
    _NP_RepositoryId = _0_protection._d_ProtectionGroupIterator_I[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_protection.ProtectionGroupIterator_I = ProtectionGroupIterator_I
_0_protection._tc_ProtectionGroupIterator_I = omniORB.tcInternal.createTypeCode(_0_protection._d_ProtectionGroupIterator_I)
omniORB.registerType(ProtectionGroupIterator_I._NP_RepositoryId, _0_protection._d_ProtectionGroupIterator_I, _0_protection._tc_ProtectionGroupIterator_I)

# ProtectionGroupIterator_I operations and attributes
ProtectionGroupIterator_I._d_next_n = ((omniORB.tcInternal.tv_ulong, ), (omniORB.tcInternal.tv_boolean, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionGroupList_T:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionGroupIterator_I._d_getLength = ((), (omniORB.tcInternal.tv_ulong, ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionGroupIterator_I._d_destroy = ((), (), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})

# ProtectionGroupIterator_I object reference
class _objref_ProtectionGroupIterator_I (CORBA.Object):
    _NP_RepositoryId = ProtectionGroupIterator_I._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def next_n(self, *args):
        return _omnipy.invoke(self, "next_n", _0_protection.ProtectionGroupIterator_I._d_next_n, args)

    def getLength(self, *args):
        return _omnipy.invoke(self, "getLength", _0_protection.ProtectionGroupIterator_I._d_getLength, args)

    def destroy(self, *args):
        return _omnipy.invoke(self, "destroy", _0_protection.ProtectionGroupIterator_I._d_destroy, args)

    __methods__ = ["next_n", "getLength", "destroy"] + CORBA.Object.__methods__

omniORB.registerObjref(ProtectionGroupIterator_I._NP_RepositoryId, _objref_ProtectionGroupIterator_I)
_0_protection._objref_ProtectionGroupIterator_I = _objref_ProtectionGroupIterator_I
del ProtectionGroupIterator_I, _objref_ProtectionGroupIterator_I

# ProtectionGroupIterator_I skeleton
__name__ = "protection__POA"
class ProtectionGroupIterator_I (PortableServer.Servant):
    _NP_RepositoryId = _0_protection.ProtectionGroupIterator_I._NP_RepositoryId


    _omni_op_d = {"next_n": _0_protection.ProtectionGroupIterator_I._d_next_n, "getLength": _0_protection.ProtectionGroupIterator_I._d_getLength, "destroy": _0_protection.ProtectionGroupIterator_I._d_destroy}

ProtectionGroupIterator_I._omni_skeleton = ProtectionGroupIterator_I
_0_protection__POA.ProtectionGroupIterator_I = ProtectionGroupIterator_I
omniORB.registerSkeleton(ProtectionGroupIterator_I._NP_RepositoryId, ProtectionGroupIterator_I)
del ProtectionGroupIterator_I
__name__ = "protection"

# interface ProtectionSubnetworkIterator_I
_0_protection._d_ProtectionSubnetworkIterator_I = (omniORB.tcInternal.tv_objref, "IDL:mtnm.tmforum.org/protection/ProtectionSubnetworkIterator_I:1.0", "ProtectionSubnetworkIterator_I")
omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionSubnetworkIterator_I:1.0"] = _0_protection._d_ProtectionSubnetworkIterator_I
_0_protection.ProtectionSubnetworkIterator_I = omniORB.newEmptyClass()
class ProtectionSubnetworkIterator_I :
    _NP_RepositoryId = _0_protection._d_ProtectionSubnetworkIterator_I[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_protection.ProtectionSubnetworkIterator_I = ProtectionSubnetworkIterator_I
_0_protection._tc_ProtectionSubnetworkIterator_I = omniORB.tcInternal.createTypeCode(_0_protection._d_ProtectionSubnetworkIterator_I)
omniORB.registerType(ProtectionSubnetworkIterator_I._NP_RepositoryId, _0_protection._d_ProtectionSubnetworkIterator_I, _0_protection._tc_ProtectionSubnetworkIterator_I)

# ProtectionSubnetworkIterator_I operations and attributes
ProtectionSubnetworkIterator_I._d_next_n = ((omniORB.tcInternal.tv_ulong, ), (omniORB.tcInternal.tv_boolean, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionSubnetworkList_T:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionSubnetworkIterator_I._d_getLength = ((), (omniORB.tcInternal.tv_ulong, ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionSubnetworkIterator_I._d_destroy = ((), (), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})

# ProtectionSubnetworkIterator_I object reference
class _objref_ProtectionSubnetworkIterator_I (CORBA.Object):
    _NP_RepositoryId = ProtectionSubnetworkIterator_I._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def next_n(self, *args):
        return _omnipy.invoke(self, "next_n", _0_protection.ProtectionSubnetworkIterator_I._d_next_n, args)

    def getLength(self, *args):
        return _omnipy.invoke(self, "getLength", _0_protection.ProtectionSubnetworkIterator_I._d_getLength, args)

    def destroy(self, *args):
        return _omnipy.invoke(self, "destroy", _0_protection.ProtectionSubnetworkIterator_I._d_destroy, args)

    __methods__ = ["next_n", "getLength", "destroy"] + CORBA.Object.__methods__

omniORB.registerObjref(ProtectionSubnetworkIterator_I._NP_RepositoryId, _objref_ProtectionSubnetworkIterator_I)
_0_protection._objref_ProtectionSubnetworkIterator_I = _objref_ProtectionSubnetworkIterator_I
del ProtectionSubnetworkIterator_I, _objref_ProtectionSubnetworkIterator_I

# ProtectionSubnetworkIterator_I skeleton
__name__ = "protection__POA"
class ProtectionSubnetworkIterator_I (PortableServer.Servant):
    _NP_RepositoryId = _0_protection.ProtectionSubnetworkIterator_I._NP_RepositoryId


    _omni_op_d = {"next_n": _0_protection.ProtectionSubnetworkIterator_I._d_next_n, "getLength": _0_protection.ProtectionSubnetworkIterator_I._d_getLength, "destroy": _0_protection.ProtectionSubnetworkIterator_I._d_destroy}

ProtectionSubnetworkIterator_I._omni_skeleton = ProtectionSubnetworkIterator_I
_0_protection__POA.ProtectionSubnetworkIterator_I = ProtectionSubnetworkIterator_I
omniORB.registerSkeleton(ProtectionSubnetworkIterator_I._NP_RepositoryId, ProtectionSubnetworkIterator_I)
del ProtectionSubnetworkIterator_I
__name__ = "protection"

# interface WDMProtectionGroupIterator_I
_0_protection._d_WDMProtectionGroupIterator_I = (omniORB.tcInternal.tv_objref, "IDL:mtnm.tmforum.org/protection/WDMProtectionGroupIterator_I:1.0", "WDMProtectionGroupIterator_I")
omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/WDMProtectionGroupIterator_I:1.0"] = _0_protection._d_WDMProtectionGroupIterator_I
_0_protection.WDMProtectionGroupIterator_I = omniORB.newEmptyClass()
class WDMProtectionGroupIterator_I :
    _NP_RepositoryId = _0_protection._d_WDMProtectionGroupIterator_I[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_protection.WDMProtectionGroupIterator_I = WDMProtectionGroupIterator_I
_0_protection._tc_WDMProtectionGroupIterator_I = omniORB.tcInternal.createTypeCode(_0_protection._d_WDMProtectionGroupIterator_I)
omniORB.registerType(WDMProtectionGroupIterator_I._NP_RepositoryId, _0_protection._d_WDMProtectionGroupIterator_I, _0_protection._tc_WDMProtectionGroupIterator_I)

# WDMProtectionGroupIterator_I operations and attributes
WDMProtectionGroupIterator_I._d_next_n = ((omniORB.tcInternal.tv_ulong, ), (omniORB.tcInternal.tv_boolean, omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/WDMProtectionGroupList_T:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
WDMProtectionGroupIterator_I._d_getLength = ((), (omniORB.tcInternal.tv_ulong, ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
WDMProtectionGroupIterator_I._d_destroy = ((), (), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})

# WDMProtectionGroupIterator_I object reference
class _objref_WDMProtectionGroupIterator_I (CORBA.Object):
    _NP_RepositoryId = WDMProtectionGroupIterator_I._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def next_n(self, *args):
        return _omnipy.invoke(self, "next_n", _0_protection.WDMProtectionGroupIterator_I._d_next_n, args)

    def getLength(self, *args):
        return _omnipy.invoke(self, "getLength", _0_protection.WDMProtectionGroupIterator_I._d_getLength, args)

    def destroy(self, *args):
        return _omnipy.invoke(self, "destroy", _0_protection.WDMProtectionGroupIterator_I._d_destroy, args)

    __methods__ = ["next_n", "getLength", "destroy"] + CORBA.Object.__methods__

omniORB.registerObjref(WDMProtectionGroupIterator_I._NP_RepositoryId, _objref_WDMProtectionGroupIterator_I)
_0_protection._objref_WDMProtectionGroupIterator_I = _objref_WDMProtectionGroupIterator_I
del WDMProtectionGroupIterator_I, _objref_WDMProtectionGroupIterator_I

# WDMProtectionGroupIterator_I skeleton
__name__ = "protection__POA"
class WDMProtectionGroupIterator_I (PortableServer.Servant):
    _NP_RepositoryId = _0_protection.WDMProtectionGroupIterator_I._NP_RepositoryId


    _omni_op_d = {"next_n": _0_protection.WDMProtectionGroupIterator_I._d_next_n, "getLength": _0_protection.WDMProtectionGroupIterator_I._d_getLength, "destroy": _0_protection.WDMProtectionGroupIterator_I._d_destroy}

WDMProtectionGroupIterator_I._omni_skeleton = WDMProtectionGroupIterator_I
_0_protection__POA.WDMProtectionGroupIterator_I = WDMProtectionGroupIterator_I
omniORB.registerSkeleton(WDMProtectionGroupIterator_I._NP_RepositoryId, WDMProtectionGroupIterator_I)
del WDMProtectionGroupIterator_I
__name__ = "protection"

# interface ProtectionMgr_I
_0_protection._d_ProtectionMgr_I = (omniORB.tcInternal.tv_objref, "IDL:mtnm.tmforum.org/protection/ProtectionMgr_I:1.0", "ProtectionMgr_I")
omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionMgr_I:1.0"] = _0_protection._d_ProtectionMgr_I
_0_protection.ProtectionMgr_I = omniORB.newEmptyClass()
class ProtectionMgr_I (_0_common.Common_I):
    _NP_RepositoryId = _0_protection._d_ProtectionMgr_I[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_protection.ProtectionMgr_I = ProtectionMgr_I
_0_protection._tc_ProtectionMgr_I = omniORB.tcInternal.createTypeCode(_0_protection._d_ProtectionMgr_I)
omniORB.registerType(ProtectionMgr_I._NP_RepositoryId, _0_protection._d_ProtectionMgr_I, _0_protection._tc_ProtectionMgr_I)

# ProtectionMgr_I operations and attributes
ProtectionMgr_I._d_getAllProtectionGroups = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], omniORB.tcInternal.tv_ulong), (omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionGroupList_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionGroupIterator_I:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionMgr_I._d_getProtectionGroup = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], ), (omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionGroup_T:1.0"], ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionMgr_I._d_setProtectionGroup = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0"]), (omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionGroup_T:1.0"], ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionMgr_I._d_getAllNUTTPNames = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], omniORB.tcInternal.tv_ulong), (omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributesList_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributesIterator_I:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionMgr_I._d_getAllPreemptibleTPNames = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], omniORB.tcInternal.tv_ulong), (omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributesList_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributesIterator_I:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionMgr_I._d_getAllProtectedTPNames = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], omniORB.tcInternal.tv_ulong), (omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributesList_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributesIterator_I:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionMgr_I._d_retrieveSwitchData = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], ), (omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/SwitchDataList_T:1.0"], ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionMgr_I._d_performProtectionCommand = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionCommand_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"]), (omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/SwitchData_T:1.0"], ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionMgr_I._d_getAdjacentTPs = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], ), (omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributesList_T:1.0"], ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionMgr_I._d_getAllEProtectionGroups = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], omniORB.tcInternal.tv_ulong), (omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/EProtectionGroupList_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/EProtectionGroupIterator_I:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionMgr_I._d_getEProtectionGroup = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], ), (omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/EProtectionGroup_T:1.0"], ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionMgr_I._d_retrieveESwitchData = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], ), (omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ESwitchDataList_T:1.0"], ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionMgr_I._d_getAllProtectionSubnetworks = ((omniORB.tcInternal.tv_ulong, ), (omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionSubnetworkList_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionSubnetworkIterator_I:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionMgr_I._d_getAllWDMProtectionGroups = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], omniORB.tcInternal.tv_ulong), (omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/WDMProtectionGroupList_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/WDMProtectionGroupIterator_I:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionMgr_I._d_getWDMProtectionGroup = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], ), (omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/WDMProtectionGroup_T:1.0"], ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionMgr_I._d_retrieveWDMSwitchData = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], ), (omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/WDMSwitchDataList_T:1.0"], ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
ProtectionMgr_I._d_performWDMProtectionCommand = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/ProtectionCommand_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"]), (omniORB.typeMapping["IDL:mtnm.tmforum.org/protection/WDMSwitchData_T:1.0"], ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})

# ProtectionMgr_I object reference
class _objref_ProtectionMgr_I (_0_common._objref_Common_I):
    _NP_RepositoryId = ProtectionMgr_I._NP_RepositoryId

    def __init__(self):
        _0_common._objref_Common_I.__init__(self)

    def getAllProtectionGroups(self, *args):
        return _omnipy.invoke(self, "getAllProtectionGroups", _0_protection.ProtectionMgr_I._d_getAllProtectionGroups, args)

    def getProtectionGroup(self, *args):
        return _omnipy.invoke(self, "getProtectionGroup", _0_protection.ProtectionMgr_I._d_getProtectionGroup, args)

    def setProtectionGroup(self, *args):
        return _omnipy.invoke(self, "setProtectionGroup", _0_protection.ProtectionMgr_I._d_setProtectionGroup, args)

    def getAllNUTTPNames(self, *args):
        return _omnipy.invoke(self, "getAllNUTTPNames", _0_protection.ProtectionMgr_I._d_getAllNUTTPNames, args)

    def getAllPreemptibleTPNames(self, *args):
        return _omnipy.invoke(self, "getAllPreemptibleTPNames", _0_protection.ProtectionMgr_I._d_getAllPreemptibleTPNames, args)

    def getAllProtectedTPNames(self, *args):
        return _omnipy.invoke(self, "getAllProtectedTPNames", _0_protection.ProtectionMgr_I._d_getAllProtectedTPNames, args)

    def retrieveSwitchData(self, *args):
        return _omnipy.invoke(self, "retrieveSwitchData", _0_protection.ProtectionMgr_I._d_retrieveSwitchData, args)

    def performProtectionCommand(self, *args):
        return _omnipy.invoke(self, "performProtectionCommand", _0_protection.ProtectionMgr_I._d_performProtectionCommand, args)

    def getAdjacentTPs(self, *args):
        return _omnipy.invoke(self, "getAdjacentTPs", _0_protection.ProtectionMgr_I._d_getAdjacentTPs, args)

    def getAllEProtectionGroups(self, *args):
        return _omnipy.invoke(self, "getAllEProtectionGroups", _0_protection.ProtectionMgr_I._d_getAllEProtectionGroups, args)

    def getEProtectionGroup(self, *args):
        return _omnipy.invoke(self, "getEProtectionGroup", _0_protection.ProtectionMgr_I._d_getEProtectionGroup, args)

    def retrieveESwitchData(self, *args):
        return _omnipy.invoke(self, "retrieveESwitchData", _0_protection.ProtectionMgr_I._d_retrieveESwitchData, args)

    def getAllProtectionSubnetworks(self, *args):
        return _omnipy.invoke(self, "getAllProtectionSubnetworks", _0_protection.ProtectionMgr_I._d_getAllProtectionSubnetworks, args)

    def getAllWDMProtectionGroups(self, *args):
        return _omnipy.invoke(self, "getAllWDMProtectionGroups", _0_protection.ProtectionMgr_I._d_getAllWDMProtectionGroups, args)

    def getWDMProtectionGroup(self, *args):
        return _omnipy.invoke(self, "getWDMProtectionGroup", _0_protection.ProtectionMgr_I._d_getWDMProtectionGroup, args)

    def retrieveWDMSwitchData(self, *args):
        return _omnipy.invoke(self, "retrieveWDMSwitchData", _0_protection.ProtectionMgr_I._d_retrieveWDMSwitchData, args)

    def performWDMProtectionCommand(self, *args):
        return _omnipy.invoke(self, "performWDMProtectionCommand", _0_protection.ProtectionMgr_I._d_performWDMProtectionCommand, args)

    __methods__ = ["getAllProtectionGroups", "getProtectionGroup", "setProtectionGroup", "getAllNUTTPNames", "getAllPreemptibleTPNames", "getAllProtectedTPNames", "retrieveSwitchData", "performProtectionCommand", "getAdjacentTPs", "getAllEProtectionGroups", "getEProtectionGroup", "retrieveESwitchData", "getAllProtectionSubnetworks", "getAllWDMProtectionGroups", "getWDMProtectionGroup", "retrieveWDMSwitchData", "performWDMProtectionCommand"] + _0_common._objref_Common_I.__methods__

omniORB.registerObjref(ProtectionMgr_I._NP_RepositoryId, _objref_ProtectionMgr_I)
_0_protection._objref_ProtectionMgr_I = _objref_ProtectionMgr_I
del ProtectionMgr_I, _objref_ProtectionMgr_I

# ProtectionMgr_I skeleton
__name__ = "protection__POA"
class ProtectionMgr_I (_0_common__POA.Common_I):
    _NP_RepositoryId = _0_protection.ProtectionMgr_I._NP_RepositoryId


    _omni_op_d = {"getAllProtectionGroups": _0_protection.ProtectionMgr_I._d_getAllProtectionGroups, "getProtectionGroup": _0_protection.ProtectionMgr_I._d_getProtectionGroup, "setProtectionGroup": _0_protection.ProtectionMgr_I._d_setProtectionGroup, "getAllNUTTPNames": _0_protection.ProtectionMgr_I._d_getAllNUTTPNames, "getAllPreemptibleTPNames": _0_protection.ProtectionMgr_I._d_getAllPreemptibleTPNames, "getAllProtectedTPNames": _0_protection.ProtectionMgr_I._d_getAllProtectedTPNames, "retrieveSwitchData": _0_protection.ProtectionMgr_I._d_retrieveSwitchData, "performProtectionCommand": _0_protection.ProtectionMgr_I._d_performProtectionCommand, "getAdjacentTPs": _0_protection.ProtectionMgr_I._d_getAdjacentTPs, "getAllEProtectionGroups": _0_protection.ProtectionMgr_I._d_getAllEProtectionGroups, "getEProtectionGroup": _0_protection.ProtectionMgr_I._d_getEProtectionGroup, "retrieveESwitchData": _0_protection.ProtectionMgr_I._d_retrieveESwitchData, "getAllProtectionSubnetworks": _0_protection.ProtectionMgr_I._d_getAllProtectionSubnetworks, "getAllWDMProtectionGroups": _0_protection.ProtectionMgr_I._d_getAllWDMProtectionGroups, "getWDMProtectionGroup": _0_protection.ProtectionMgr_I._d_getWDMProtectionGroup, "retrieveWDMSwitchData": _0_protection.ProtectionMgr_I._d_retrieveWDMSwitchData, "performWDMProtectionCommand": _0_protection.ProtectionMgr_I._d_performWDMProtectionCommand}
    _omni_op_d.update(_0_common__POA.Common_I._omni_op_d)

ProtectionMgr_I._omni_skeleton = ProtectionMgr_I
_0_protection__POA.ProtectionMgr_I = ProtectionMgr_I
omniORB.registerSkeleton(ProtectionMgr_I._NP_RepositoryId, ProtectionMgr_I)
del ProtectionMgr_I
__name__ = "protection"

#
# End of module "protection"
#
__name__ = "protection_idl"

_exported_modules = ( "protection", )

# The end.
