# Python stubs generated by omniidl from session.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "session"
#
__name__ = "session"
_0_session = omniORB.openModule("session", r"session.idl")
_0_session__POA = omniORB.openModule("session__POA", r"session.idl")


# interface Session_I
_0_session._d_Session_I = (omniORB.tcInternal.tv_objref, "IDL:mtnm.tmforum.org/session/Session_I:1.0", "Session_I")
omniORB.typeMapping["IDL:mtnm.tmforum.org/session/Session_I:1.0"] = _0_session._d_Session_I
_0_session.Session_I = omniORB.newEmptyClass()
class Session_I :
    _NP_RepositoryId = _0_session._d_Session_I[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_session.Session_I = Session_I
_0_session._tc_Session_I = omniORB.tcInternal.createTypeCode(_0_session._d_Session_I)
omniORB.registerType(Session_I._NP_RepositoryId, _0_session._d_Session_I, _0_session._tc_Session_I)

# Session_I operations and attributes
Session_I._d__get_associatedSession = ((),(omniORB.typeMapping["IDL:mtnm.tmforum.org/session/Session_I:1.0"],),None)
Session_I._d_ping = ((), (), None)
Session_I._d_endSession = ((), None, None)

# Session_I object reference
class _objref_Session_I (CORBA.Object):
    _NP_RepositoryId = Session_I._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def _get_associatedSession(self, *args):
        return _omnipy.invoke(self, "_get_associatedSession", _0_session.Session_I._d__get_associatedSession, args)

    def ping(self, *args):
        return _omnipy.invoke(self, "ping", _0_session.Session_I._d_ping, args)

    def endSession(self, *args):
        return _omnipy.invoke(self, "endSession", _0_session.Session_I._d_endSession, args)

    __methods__ = ["_get_associatedSession", "ping", "endSession"] + CORBA.Object.__methods__

omniORB.registerObjref(Session_I._NP_RepositoryId, _objref_Session_I)
_0_session._objref_Session_I = _objref_Session_I
del Session_I, _objref_Session_I

# Session_I skeleton
__name__ = "session__POA"
class Session_I (PortableServer.Servant):
    _NP_RepositoryId = _0_session.Session_I._NP_RepositoryId


    _omni_op_d = {"_get_associatedSession": _0_session.Session_I._d__get_associatedSession, "ping": _0_session.Session_I._d_ping, "endSession": _0_session.Session_I._d_endSession}

Session_I._omni_skeleton = Session_I
_0_session__POA.Session_I = Session_I
omniORB.registerSkeleton(Session_I._NP_RepositoryId, Session_I)
del Session_I
__name__ = "session"

#
# End of module "session"
#
__name__ = "session_idl"

_exported_modules = ( "session", )

# The end.
