# Python stubs generated by omniidl from transmissionParameters.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)

# #include "globaldefs.idl"
import globaldefs_idl
_0_globaldefs = omniORB.openModule("globaldefs")
_0_globaldefs__POA = omniORB.openModule("globaldefs__POA")

#
# Start of module "transmissionParameters"
#
__name__ = "transmissionParameters"
_0_transmissionParameters = omniORB.openModule("transmissionParameters", r"transmissionParameters.idl")
_0_transmissionParameters__POA = omniORB.openModule("transmissionParameters__POA", r"transmissionParameters.idl")


# typedef ... LayerRate_T
class LayerRate_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/transmissionParameters/LayerRate_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_transmissionParameters.LayerRate_T = LayerRate_T
_0_transmissionParameters._d_LayerRate_T  = omniORB.tcInternal.tv_short
_0_transmissionParameters._ad_LayerRate_T = (omniORB.tcInternal.tv_alias, LayerRate_T._NP_RepositoryId, "LayerRate_T", omniORB.tcInternal.tv_short)
_0_transmissionParameters._tc_LayerRate_T = omniORB.tcInternal.createTypeCode(_0_transmissionParameters._ad_LayerRate_T)
omniORB.registerType(LayerRate_T._NP_RepositoryId, _0_transmissionParameters._ad_LayerRate_T, _0_transmissionParameters._tc_LayerRate_T)
del LayerRate_T

# typedef ... LayerRateList_T
class LayerRateList_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/transmissionParameters/LayerRateList_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_transmissionParameters.LayerRateList_T = LayerRateList_T
_0_transmissionParameters._d_LayerRateList_T  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/transmissionParameters/LayerRate_T:1.0"], 0)
_0_transmissionParameters._ad_LayerRateList_T = (omniORB.tcInternal.tv_alias, LayerRateList_T._NP_RepositoryId, "LayerRateList_T", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/transmissionParameters/LayerRate_T:1.0"], 0))
_0_transmissionParameters._tc_LayerRateList_T = omniORB.tcInternal.createTypeCode(_0_transmissionParameters._ad_LayerRateList_T)
omniORB.registerType(LayerRateList_T._NP_RepositoryId, _0_transmissionParameters._ad_LayerRateList_T, _0_transmissionParameters._tc_LayerRateList_T)
del LayerRateList_T

# struct LayeredParameters_T
_0_transmissionParameters.LayeredParameters_T = omniORB.newEmptyClass()
class LayeredParameters_T (omniORB.StructBase):
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/transmissionParameters/LayeredParameters_T:1.0"

    def __init__(self, layer, transmissionParams):
        self.layer = layer
        self.transmissionParams = transmissionParams

_0_transmissionParameters.LayeredParameters_T = LayeredParameters_T
_0_transmissionParameters._d_LayeredParameters_T  = (omniORB.tcInternal.tv_struct, LayeredParameters_T, LayeredParameters_T._NP_RepositoryId, "LayeredParameters_T", "layer", omniORB.typeMapping["IDL:mtnm.tmforum.org/transmissionParameters/LayerRate_T:1.0"], "transmissionParams", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0"])
_0_transmissionParameters._tc_LayeredParameters_T = omniORB.tcInternal.createTypeCode(_0_transmissionParameters._d_LayeredParameters_T)
omniORB.registerType(LayeredParameters_T._NP_RepositoryId, _0_transmissionParameters._d_LayeredParameters_T, _0_transmissionParameters._tc_LayeredParameters_T)
del LayeredParameters_T

# typedef ... LayeredParameterList_T
class LayeredParameterList_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/transmissionParameters/LayeredParameterList_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_transmissionParameters.LayeredParameterList_T = LayeredParameterList_T
_0_transmissionParameters._d_LayeredParameterList_T  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/transmissionParameters/LayeredParameters_T:1.0"], 0)
_0_transmissionParameters._ad_LayeredParameterList_T = (omniORB.tcInternal.tv_alias, LayeredParameterList_T._NP_RepositoryId, "LayeredParameterList_T", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/transmissionParameters/LayeredParameters_T:1.0"], 0))
_0_transmissionParameters._tc_LayeredParameterList_T = omniORB.tcInternal.createTypeCode(_0_transmissionParameters._ad_LayeredParameterList_T)
omniORB.registerType(LayeredParameterList_T._NP_RepositoryId, _0_transmissionParameters._ad_LayeredParameterList_T, _0_transmissionParameters._tc_LayeredParameterList_T)
del LayeredParameterList_T

#
# End of module "transmissionParameters"
#
__name__ = "transmissionParameters_idl"

_exported_modules = ( "transmissionParameters", )

# The end.
