# DO NOT EDIT THIS FILE!
#
# Python module common__POA generated by omniidl

import omniORB
omniORB.updateModule("common__POA")

# ** 1. Stub files contributing to this module
import common_idl

# ** 2. Sub-modules

# ** 3. End
