# Python stubs generated by omniidl from orb.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)

_exported_modules = ( )

# The end.
