# DO NOT EDIT THIS FILE!
#
# Python module protection__POA generated by omniidl

import omniORB
omniORB.updateModule("protection__POA")

# ** 1. Stub files contributing to this module
import protection_idl

# ** 2. Sub-modules

# ** 3. End
