# DO NOT EDIT THIS FILE!
#
# Python module managedElement__POA generated by omniidl

import omniORB
omniORB.updateModule("managedElement__POA")

# ** 1. Stub files contributing to this module
import managedElement_idl

# ** 2. Sub-modules

# ** 3. End
